version: "3"
services:
  db:
    image: mysql:5.7.24
    environment:
      - MYSQL_ROOT_PASSWORD=password
  redis:
    image: redis:latest
    ports:
      - 63980:6379
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bash"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - ../gem:/gem/
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin1
    links:
      - db:mysql
    restart: always
    ports:
      - 28080:80
